# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ventacedis_pb2 as ventacedis__pb2


class dbStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.dbData = channel.unary_unary(
        '/ventas_cedis.db/dbData',
        request_serializer=ventacedis__pb2.Params.SerializeToString,
        response_deserializer=ventacedis__pb2.Response.FromString,
        )


class dbServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def dbData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_dbServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'dbData': grpc.unary_unary_rpc_method_handler(
          servicer.dbData,
          request_deserializer=ventacedis__pb2.Params.FromString,
          response_serializer=ventacedis__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ventas_cedis.db', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
