# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ventacedis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ventacedis.proto',
  package='ventas_cedis',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10ventacedis.proto\x12\x0cventas_cedis\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\x08\"\x17\n\x06Params\x12\r\n\x05value\x18\x01 \x01(\x08\x32>\n\x02\x64\x62\x12\x38\n\x06\x64\x62\x44\x61ta\x12\x14.ventas_cedis.Params\x1a\x16.ventas_cedis.Response\"\x00\x62\x06proto3')
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='ventas_cedis.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ventas_cedis.Response.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=59,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='ventas_cedis.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ventas_cedis.Params.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'ventacedis_pb2'
  # @@protoc_insertion_point(class_scope:ventas_cedis.Response)
  })
_sym_db.RegisterMessage(Response)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'ventacedis_pb2'
  # @@protoc_insertion_point(class_scope:ventas_cedis.Params)
  })
_sym_db.RegisterMessage(Params)



_DB = _descriptor.ServiceDescriptor(
  name='db',
  full_name='ventas_cedis.db',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='dbData',
    full_name='ventas_cedis.db.dbData',
    index=0,
    containing_service=None,
    input_type=_PARAMS,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DB)

DESCRIPTOR.services_by_name['db'] = _DB

# @@protoc_insertion_point(module_scope)
